### ISSUE TITLE
The server is too slow and sometime timeout

### ISSUE THREAD

**Issue by cyfung1031** [greasyfork-org/greasyfork#1334]
<img width="695" alt="Screen Shot 2024-10-12 at 10 57 36" src="https://github.com/user-attachments/assets/ff2a99f6-e098-4a67-a465-0d926f00b099">

**Comment by cyfung1031** [comment]
The issue does not just affect the user browsing. The webhook from GitHub could not reach to greasyfork.org, so the version remains the old one without update.

**Comment by cyfung1031** [comment]
Now the server connection restores. 

The webhook for the previous commit was dropped.

<img width="707" alt="Screen Shot 2024-10-12 at 12 16 34" src="https://github.com/user-attachments/assets/50e855f3-fd7f-47d5-b980-9ce59ecbc7ad">

**Comment by JasonBarnabe** [comment]
For some reason, there are an excessive amount of requests to two particular user CSS URLs that have been deleted. With them deleted, the clients seem to request them over and over, reaching the connection limit of the site's load balancer. If I serve up a blank file, then the clients seem to go away for a while before requesting it again. So that's what I'm doing for now.
