### ISSUE TITLE
Help document: Extensions for Opera

### ISSUE THREAD

**Issue by maboroshin** [greasyfork-org/greasyfork#1336]
Opera supports add-ons for Chrome: https://github.com/operasoftware/chrome-webstore-extension 

Stylus on the addons.opera.com site is out of date. So you may want to link to the Chrome webstore: https://greasyfork.org/help/installing-user-styles

**Comment by JasonBarnabe** [comment]
@tophf What is the preferred install link for Stylus for Opera users?

**Comment by tophf** [comment]
The Chrome's web store. Because Opera's takes too long to review us, sometimes months.

stable: https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne
beta: https://chromewebstore.google.com/detail/stylus-beta/apmmpaebfobifelkijhaljbmpcgbjbdo 

I've just finished porting it to ManifestV3, so we'll publish it in the beta first.
